spring:
  application:
    name: jungjik

  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
