spring:
  application:
    name: jungjik

  datasource:
    url: ${DATASOURCE_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

slack:
  webhook:
    user-url: ${SLACK_WEBHOOK_USER_URL}
    admin-url: ${SLACK_WEBHOOK_ADMIN_URL}

admin:
  api:
    token: ${ADMIN_API_TOKEN}